/**
 * Payment Service for UPIGateway Integration
 */

const API_KEY = 'c2634cc5-0041-4637-9af4-c1089c115e13';
const BASE_URL = '/api/upi';

/**
 * Creates a payment order with UPIGateway
 * @param {Object} params - Order parameters (amount, client_txn_id, customer_name, etc.)
 * @returns {Promise<Object>} - API response data
 */
export const createOrder = async (params) => {
    try {
        const response = await fetch(`${BASE_URL}/create_order`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                key: API_KEY,
                ...params,
                p_info: params.p_info || 'Print Job',
            }),
        });

        const result = await response.json();
        return result;
    } catch (error) {
        console.error('UPIGateway Create Order Error:', error);
        if (error.response) {
            const errData = await error.response.json().catch(() => ({}));
            console.error('Server Error Details:', errData);
        }
        throw error;
    }
};

/**
 * Checks the status of a transaction
 * @param {string} client_txn_id - Unique transaction ID generated by the client
 * @param {string} txn_date - Date of transaction (YYYY-MM-DD)
 * @returns {Promise<Object>} - Status response
 */
export const checkStatus = async (client_txn_id, txn_date) => {
    try {
        const response = await fetch(`${BASE_URL}/check_order_status`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                key: API_KEY,
                client_txn_id,
                txn_date,
            }),
        });

        const result = await response.json();
        return result;
    } catch (error) {
        console.error('UPIGateway Check Status Error:', error);
        throw error;
    }
};
